name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Btrfs CI
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
      id: go

    - name: Setup environment
      shell: bash
      run: |
        echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

    - name: Check out code
      uses: actions/checkout@v2
      with:
        path: src/github.com/containerd/btrfs
        fetch-depth: 25

    - name: Project checks
      uses: containerd/project-checks@v1
      # Disabled during repo migration
      if: false
      with:
        working-directory: src/github.com/containerd/btrfs

    - name: Test
      working-directory: src/github.com/containerd/btrfs
      run: |
        sudo go test -v ./...

    - name: Build gbtrfs
      working-directory: src/github.com/containerd/btrfs/cmd/gbtrfs
      run: |
        go build .
